### ISSUE TITLE
ERC20 program in Cairo (easy!)

### ISSUE THREAD

**Issue by s0lness** [Hyle-org/examples#3] opened 2024-08-20 18:34 UTC
Write a program to manage ERC20 tokens in Cairo, and deploy it on Hylé.
Here's the documentation to code [your 1st smart contract on Hylé](https://docs.hyle.eu/developers/using-the-cli/your-first-smart-contract/).

We actually already wrote it! Here's the [example of the Cairo ERC20 contract](https://github.com/Hyle-org/vibe-check/tree/main/cairo-smile-token) used for the [vibe check demo](https://vibe.hyle.eu/). You just have to package the code in this repo properly, under the correct folder, and update the readme to point to it.

**Comment by od-hunter** [comment] 2024-08-21 11:51
Hi @s0lness ,Can I work on this please?

**Comment by Calebux** [comment] 2024-08-21 23:00
@s0lness can I be assigned to this issue I’d deliver on time.

**Comment by ikemHood** [comment] 2024-08-22 08:23
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hey, I am ikem Peter. a fullstack software developer with 3+ years of working experience, I would love to help out with this issue...

### How I plan on tackling this issue
I would implement every requirement of a ERC20 in cairo smart contract

**Comment by MatiasAchucarro** [comment] 2024-08-22 08:33
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

This will be my first contribution to the open-source ecosystem, and I am excited to learn and collaborate on innovative projects, particularly those involving Cairo

### How I plan on tackling this issue
To manage ERC20 tokens in Cairo and implement it in Hylé, I would start by packaging the already written ERC20 contract. I’d place the code in the correct folder within the Hylé repository, following the project's structure. Then, I’d update the README file to include a section pointing to the new contract, detailing its location and usage. Finally, I’d test the contract to ensure it works correctly in the Hylé environment.

**Comment by od-hunter** [comment] 2024-08-22 08:51
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a passionate fullstack developer with vast experience and I'd love to be given the opportunity to prove my skills.

### How I plan on tackling this issue
To solve this issue I'd make sure to implement every requirement of a ERC20 in cairo smart contract.
I am ready to package the code properly and update README to indicate. Lastly, I'll test to make sure everything is in order. Please assign me I am ready to work.

**Comment by PoulavBhowmick03** [comment] 2024-08-22 10:18
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

### How I plan on tackling this issue
I will work on this issue by taking the following steps:

1. Package the Existing Cairo ERC20 Contract
I’ll start by organizing the existing Cairo ERC20 contract code, which was used in the vibe check demo, into the appropriate folder within the repository.
I will ensure that the structure adheres to the repository’s standards and is easy to navigate for other contributors.
2. Update the README
I’ll update the README file to reflect the changes and provide clear instructions on how to find and use the ERC20 contract within the repository.
This will include details on how to compile, deploy, and interact with the contract using the Hylé platform.
3. Test the Contract on Hylé
I will follow the provided documentation to deploy the ERC20 contract on the Hylé devnet.
This will involve registering the contract on-chain and verifying that it functions correctly through stateful transactions.
I’ll document the deployment process and include it in the README for future reference.
4. Documentation and Code Cleanup
After the contract is successfully deployed, I will clean up the codebase if needed, removing any redundant comments or unused imports.
I’ll make sure the code is well-documented, with comments explaining key sections and logic.

**Comment by LazarusAA** [comment] 2024-08-22 10:38
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm a motivated developer with experience in rust, JavaScript, typescript, solidity and Cairo. This is my first time contributing to Hyle and Id love to work on this issue.

### How I plan on tackling this issue
- Package the code correctly
- Update the readme 
- Check everything works as intended

Thank you for your consideration.

**Comment by jorgezerpa** [comment] 2024-08-22 11:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm a 4 years experience full-stack software developer, focused on build web and mobile applications. 

I'm starting my web3 journy, here are some related projects I built in Cairo and solidity:

* https://github.com/jorgezerpa/balt-token
* https://github.com/jorgezerpa/starknet_start
* https://github.com/jorgezerpa/cairo_cheat_sheet

Even if I'm starting on web3, I have already a lot of experience working on web and mobile projects, so everything related with code quality, git flows (PR, good commit messages, etc) and nice remote communication skills... It's a piece of cake for me.



### How I plan on tackling this issue
1. I will create a file "Cairo-smile-token" then put all code inside of it 

Since the contract for this is already coded, I think that step one is what you need primarly to submit a PR.

However, if it is needed (please confirm) I can:

2. I can test the contract. 
3. Update the readme to explain the installation steps and how to run/test the project or to add a link to the official docs https://docs.hyle.eu/developers/using-the-cli/your-first-smart-contract/


I await your response, Happy coding :)

**Comment by SoarinSkySagar** [comment] 2024-08-22 19:58
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a full stack web3 developer with experience in developing dapps. I have also contributed to core ETH repos on Golang and Rust clients.

### How I plan on tackling this issue
This is a simple issue as it only required you to package the code in the repo properly. In addition to that, I will also make sure that:
1. Code is well documented
2. Error free, if any
3. readable

**Comment by MullerTheScientist** [comment] 2024-08-22 20:43
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a full-stack developer with experience in different languages, such as Python, Cairo, Solidity, and JavaScript.

### How I plan on tackling this issue
I will Review Existing Code:
I am going to Study the provided Cairo ERC20 contract code.
Understand its functionality and ensure it meets the requirements.
and also Write a clear and concise description of the project and its functionality.
Provide instructions on how to deploy and use the ERC20 token manager.
Update the readme to point to the packaged contract code.

**Comment by JuanPabloRodriguezC** [comment] 2024-08-23 14:23
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a computer engineer student with a lot of experience on low and high level languages. I have been learning cairo and rust in the last few months, I am already familiar with all the documentation, I completed most of starklings exercises.

### How I plan on tackling this issue
-Install CLI tools
-Write smart contract using RISC Zero Collatz conjecture and following Cairo documentation
-Deploy on Hylé

**Comment by CollinsC1O** [comment] 2024-08-23 21:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm a frontend and a blockchain developer(I'm skilled with solidity and cairo)  and I will love to work on this

**Comment by mamicho16** [comment] 2024-08-25 06:27
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a developer with experience in Rust, JavaScript, TypeScript, Solidity, and Cairo. My background in web development, coupled with my growing expertise in Cairo, positions me well to contribute effectively to this project. Although this will be my first contribution to Hylé, I am eager to collaborate on innovative projects and learn from the community.

### How I plan on tackling this issue
To manage ERC20 tokens in Cairo and deploy them on Hylé, I would take the following steps:

Package the Code: Start by properly packaging the already written ERC20 contract into the correct folder within the Hylé repository, adhering to the project's structure and guidelines.

Update the README: I would update the README file to include a section that points to the new ERC20 contract, providing clear instructions on its location and usage within the Hylé environment.

Testing: Finally, I’d conduct thorough testing to ensure that the ERC20 contract functions as intended within the Hylé environment, making any necessary adjustments.

**Comment by s0lness** [comment] 2024-08-26 10:22
Assigned to @od-hunter!

**Comment by suhas-sensei** [comment] 2024-09-28 21:09
@s0lness i would love to work on this.

**Closed** 2024-12-10 16:58 UTC
Labels: good first issue, ODHack7
